# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GUI(object):
    def setupUi(self, GUI):
        GUI.setObjectName("GUI")
        GUI.resize(1200, 700)
        GUI.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.level_controller = QtWidgets.QSlider(GUI)
        self.level_controller.setEnabled(True)
        self.level_controller.setGeometry(QtCore.QRect(150, 540, 300, 22))
        self.level_controller.setOrientation(QtCore.Qt.Horizontal)
        self.level_controller.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.level_controller.setTickInterval(1)
        self.level_controller.setObjectName("level_controller")
        self.threshold_controller = QtWidgets.QSlider(GUI)
        self.threshold_controller.setGeometry(QtCore.QRect(150, 630, 300, 22))
        self.threshold_controller.setOrientation(QtCore.Qt.Horizontal)
        self.threshold_controller.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.threshold_controller.setObjectName("threshold_controller")
        self.input_window = QtWidgets.QLabel(GUI)
        self.input_window.setEnabled(True)
        self.input_window.setGeometry(QtCore.QRect(50, 50, 500, 400))
        self.input_window.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_window.setLineWidth(1)
        self.input_window.setMidLineWidth(0)
        self.input_window.setAlignment(QtCore.Qt.AlignCenter)
        self.input_window.setObjectName("input_window")
        self.output_window = QtWidgets.QLabel(GUI)
        self.output_window.setEnabled(True)
        self.output_window.setGeometry(QtCore.QRect(650, 50, 500, 400))
        self.output_window.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.output_window.setAlignment(QtCore.Qt.AlignCenter)
        self.output_window.setObjectName("output_window")
        self.stroke_size_controller = QtWidgets.QSlider(GUI)
        self.stroke_size_controller.setEnabled(True)
        self.stroke_size_controller.setGeometry(QtCore.QRect(750, 540, 300, 22))
        self.stroke_size_controller.setOrientation(QtCore.Qt.Horizontal)
        self.stroke_size_controller.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.stroke_size_controller.setObjectName("stroke_size_controller")
        self.browse = QtWidgets.QPushButton(GUI)
        self.browse.setGeometry(QtCore.QRect(830, 660, 120, 32))
        self.browse.setObjectName("browse")
        self.stroke_size_label = QtWidgets.QLabel(GUI)
        self.stroke_size_label.setGeometry(QtCore.QRect(1070, 540, 58, 16))
        self.stroke_size_label.setObjectName("stroke_size_label")
        self.threshold_label = QtWidgets.QLabel(GUI)
        self.threshold_label.setGeometry(QtCore.QRect(460, 630, 58, 16))
        self.threshold_label.setObjectName("threshold_label")
        self.level_label = QtWidgets.QLabel(GUI)
        self.level_label.setGeometry(QtCore.QRect(460, 540, 58, 16))
        self.level_label.setObjectName("level_label")
        self.title_input = QtWidgets.QLabel(GUI)
        self.title_input.setGeometry(QtCore.QRect(200, 10, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.title_input.setFont(font)
        self.title_input.setAlignment(QtCore.Qt.AlignCenter)
        self.title_input.setObjectName("title_input")
        self.title_output = QtWidgets.QLabel(GUI)
        self.title_output.setGeometry(QtCore.QRect(800, 10, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.title_output.setFont(font)
        self.title_output.setAlignment(QtCore.Qt.AlignCenter)
        self.title_output.setObjectName("title_output")
        self.exit = QtWidgets.QPushButton(GUI)
        self.exit.setGeometry(QtCore.QRect(1070, 660, 120, 32))
        self.exit.setObjectName("exit")
        self.reset = QtWidgets.QPushButton(GUI)
        self.reset.setGeometry(QtCore.QRect(950, 660, 120, 32))
        self.reset.setObjectName("reset")
        self.title_level = QtWidgets.QLabel(GUI)
        self.title_level.setGeometry(QtCore.QRect(240, 510, 120, 16))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.title_level.setFont(font)
        self.title_level.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title_level.setAlignment(QtCore.Qt.AlignCenter)
        self.title_level.setObjectName("title_level")
        self.title_threshold = QtWidgets.QLabel(GUI)
        self.title_threshold.setGeometry(QtCore.QRect(240, 600, 120, 16))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.title_threshold.setFont(font)
        self.title_threshold.setAlignment(QtCore.Qt.AlignCenter)
        self.title_threshold.setObjectName("title_threshold")
        self.title_stroke_size = QtWidgets.QLabel(GUI)
        self.title_stroke_size.setGeometry(QtCore.QRect(840, 510, 120, 16))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.title_stroke_size.setFont(font)
        self.title_stroke_size.setAlignment(QtCore.Qt.AlignCenter)
        self.title_stroke_size.setObjectName("title_stroke_size")
        self.level_label_1 = QtWidgets.QLabel(GUI)
        self.level_label_1.setGeometry(QtCore.QRect(150, 510, 58, 16))
        self.level_label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.level_label_1.setObjectName("level_label_1")
        self.level_label_2 = QtWidgets.QLabel(GUI)
        self.level_label_2.setGeometry(QtCore.QRect(400, 510, 58, 16))
        self.level_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.level_label_2.setObjectName("level_label_2")
        self.threshold_label_1 = QtWidgets.QLabel(GUI)
        self.threshold_label_1.setGeometry(QtCore.QRect(140, 600, 58, 16))
        self.threshold_label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.threshold_label_1.setObjectName("threshold_label_1")
        self.threshold_label_2 = QtWidgets.QLabel(GUI)
        self.threshold_label_2.setGeometry(QtCore.QRect(400, 600, 58, 16))
        self.threshold_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.threshold_label_2.setObjectName("threshold_label_2")
        self.stroke_size_label_1 = QtWidgets.QLabel(GUI)
        self.stroke_size_label_1.setGeometry(QtCore.QRect(750, 510, 58, 16))
        self.stroke_size_label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.stroke_size_label_1.setObjectName("stroke_size_label_1")
        self.stroke_size_label_2 = QtWidgets.QLabel(GUI)
        self.stroke_size_label_2.setGeometry(QtCore.QRect(1000, 510, 58, 16))
        self.stroke_size_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.stroke_size_label_2.setObjectName("stroke_size_label_2")
        self.save = QtWidgets.QPushButton(GUI)
        self.save.setGeometry(QtCore.QRect(1030, 460, 120, 32))
        self.save.setObjectName("save")

        self.retranslateUi(GUI)
        QtCore.QMetaObject.connectSlotsByName(GUI)

    def retranslateUi(self, GUI):
        _translate = QtCore.QCoreApplication.translate
        GUI.setWindowTitle(_translate("GUI", "Dialog"))
        self.input_window.setText(_translate("GUI", "Input"))
        self.output_window.setText(_translate("GUI", "Output"))
        self.browse.setText(_translate("GUI", "browse..."))
        self.stroke_size_label.setText(_translate("GUI", "TextLabel"))
        self.threshold_label.setText(_translate("GUI", "TextLabel"))
        self.level_label.setText(_translate("GUI", "TextLabel"))
        self.title_input.setText(_translate("GUI", "Original image"))
        self.title_output.setText(_translate("GUI", "Processed image"))
        self.exit.setText(_translate("GUI", "Exit"))
        self.reset.setText(_translate("GUI", "Reset"))
        self.title_level.setText(_translate("GUI", "Level"))
        self.title_threshold.setText(_translate("GUI", "Threshold"))
        self.title_stroke_size.setText(_translate("GUI", "Stroke Size"))
        self.level_label_1.setText(_translate("GUI", "Coarse"))
        self.level_label_2.setText(_translate("GUI", "Fine"))
        self.threshold_label_1.setText(_translate("GUI", "Low"))
        self.threshold_label_2.setText(_translate("GUI", "High"))
        self.stroke_size_label_1.setText(_translate("GUI", "Small"))
        self.stroke_size_label_2.setText(_translate("GUI", "Large"))
        self.save.setText(_translate("GUI", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GUI = QtWidgets.QDialog()
    ui = Ui_GUI()
    ui.setupUi(GUI)
    GUI.show()
    sys.exit(app.exec_())

